# 配置文件版本
version: 4.0.0
#主题选择, can be "default" or "cyberpunk"
variant: default
# logo可以是网址或者图片
logo: 
    text: Leganck's Blog

# 页面元数据配置
head:
    # 网站图标的URL或路径
    favicon: https://files.catbox.moe/hqluar.png
    # Web应用程序清单配置
    # https://developer.mozilla.org/en-US/docs/Web/Manifest
    manifest:
        # web应用程序的名称(默认为站点标题)
        name: 
        # web应用程序显示的名称
        # 当没有足够的空间显示全名时
        short_name: 
        # web应用程序的起始URL
        start_url: 
        # 应用程序的默认主题颜色
        theme_color: 
        # 用于显示应用程序页面的占位符背景色
        #在它的样式表加载之前
        background_color: 
        #网站的首选显示模式
        display: standalone
        #图片文件可以作为应用程序的图标用于不同的上下文
        icons:
            -
                # 图像文件的路径
                src: ''
                # 包含空格分隔的图像尺寸的字符串
                sizes: ''
                # 提示图片的媒体类型
                type: 
    # #打开图形元数据
    # https://hexo.io/docs/helpers.html#open-graph
    open_graph:
        # Page title (og:title) (optional)
        # You should leave this blank for most of the time
        title: 
        # Page type (og:type) (optional)
        # You should leave this blank for most of the time
        type: blog
        # Page URL (og:url) (optional)
        # You should leave this blank for most of the time
        url: 
        # Page cover (og:image) (optional)
        # You should leave this blank for most of the time
        image: 
        # Site name (og:site_name) (optional)
        # You should leave this blank for most of the time
        site_name: 
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author: 
        # Page description (og:description) (optional)
        # You should leave this blank for most of the time
        description: 
        # Twitter card type (twitter:card)
        twitter_card: 
        # Twitter ID (twitter:creator)
        twitter_id: 
        # Twitter Site (twitter:site)
        twitter_site: 
        # Google+ profile link (deprecated)
        google_plus: 
        # Facebook admin ID
        fb_admins: 
        # Facebook App ID
        fb_app_id: 
    # Structured data of the page
    # https://developers.google.com/search/docs/guides/intro-structured-data
    structured_data:
        # Page title (optional)
        # You should leave this blank for most of the time
        title: 
        # Page description (optional)
        # You should leave this blank for most of the time
        description: 
        # Page URL (optional)
        # You should leave this blank for most of the time
        url: 
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author: 
        # Page publisher (optional)
        # You should leave this blank for most of the time
        publisher: 
        # Page publisher logo (optional)
        # You should leave this blank for most of the time
        publisher_logo: 
        # Page images (optional)
        # You should leave this blank for most of the time
        image: 
    # Additional HTML meta tags in an array
    meta:
        # Meta tag specified in <attribute>=<value> style
        # E.g., name=theme-color;content=#123456 => <meta name="theme-color" content="#123456">
        - ''
    # 网站的RSS atom xml的URL或路径
    rss: 
# 页面顶部导航栏配置
navbar:
    # 导航菜单项
    menu:
        主页: /
        归档: /archives
        分类: /categories
        标签: /tags
        关于: /about
    # Links to be shown on the right of the navigation bar
    links:
# 页脚配置
footer:
    # #链接显示在页脚部分的右边
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/'
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: 'https://creativecommons.org/licenses/by/4.0/'
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/ppoffice/hexo-theme-icarus'
# 文章相关的配置
article:
    # 代码高亮显示设置
    highlight:
        # 代码高亮主题
        # https://github.com/highlightjs/highlight.js/tree/master/src/styles
        theme: atom-one-light
        # 显示复制代码按钮
        clipboard: true
        fold: unfolded
    # 是否显示预估文章阅读时间
    readtime: true
    # 许可
    # licenses:
    #     Creative Commons:
    #         icon: fab fa-creative-commons
    #         url: 'https://creativecommons.org/'
    #     Attribution:
    #         icon: fab fa-creative-commons-by
    #         url: 'https://creativecommons.org/licenses/by/4.0/'
    #     Noncommercial:
    #         icon: fab fa-creative-commons-nc
    #         url: 'https://creativecommons.org/licenses/by-nc/4.0/'
# 搜索插件设置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search/
search:
    type: insight
# 评论插件配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment/
comment:
    type: valine
    app_id: Lg8dO6NzzoxAeBYOYYwLdEQv-gzGzoHsz
    app_key: d6dWmonrLRJL0fugsbhJ0eTI
    placeholder: "说点什么吧..."                 # 可选填
    avatar_force: false             # 可选填
    meta: ["nick", "mail", "link"]  # 可选填
    page_size: 7                  # 可选填
    lang: zh-CN                     # 可选填
    visitor: false                  # 可选填
    highlight: true                 # 可选填
    record_ip: false                # 可选填

# 捐赠插件配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Donation/
 #donates: 
    # "Afdian.net" donate button configurations
    # -
    #     type: afdian
    #     # URL to the "Afdian.net" personal page
    #     url: ''
    # # Alipay donate button configurations
    # -
    #     type: alipay
    #     # Alipay qrcode image URL
    #     qrcode: ''
    # # "Buy me a coffee" donate button configurations
    # -
    #     type: buymeacoffee
    #     # URL to the "Buy me a coffee" page
    #     url: ''
    # # Patreon donate button configurations
    # -
    #     type: patreon
    #     # URL to the Patreon page
    #     url: ''
    # # Paypal donate button configurations
    # -
    #     type: paypal
    #     # Paypal business ID or email address
    #     business: ''
    #     # Currency code
    #     currency_code: USD
    # # Wechat donate button configurations
    # -
    #     type: wechat
    #     # Wechat qrcode image URL
    #     qrcode: ''


# 分享插件配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share/
# share:
#     type: ‘’
#     # ShareThis共享插件脚本的URL
#     install_url: ''



# 侧边栏的配置
# 请注意，侧栏只有在至少有一个小部件时才可见
sidebar:
    # 左栏的配置
    left:
        # 当页面滚动时，侧边栏是否保持在顶部
        sticky: true
    # 右栏的配置
    right:
        # 当页面滚动时，侧边栏是否保持在顶部
        sticky: true
#侧栏小部件的配置
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    # 配置小部件的配置
    -
        # 小部件应该放在哪里，左边栏还是右边栏
        position: left
        type: profile
        # 作者姓名
        author: leganck
        # 作者的标题
        author_title: 
        # 作者的当前位置
        location: 
        # 头像图像的URL或路径
        avatar: https://files.catbox.moe/hqluar.png
        # 是否显示圆角的头像
        avatar_rounded: true
        # Gravatar的电子邮件地址
        gravatar: ''
        # 下面按钮的URL或路径
        follow_link: 'https://github.com/leganck'
        # 将显示在概要文件小部件底部的链接
        social_links:
            Github:
                icon: fab fa-github
                url: 'https://github.com/leganck'
    # 目录小部件配置
    -
        # 小部件应该放在哪里，左边栏还是右边栏
        position: left
        type: toc
        # 是否显示每个标题的索引
        index: true
        # 是否在看不到子标题时将其折叠
        collapsed: true
        # 最多可显示的标题级别(1-6)
        depth: 3
 # 类别小部件的配置
    -
        # 小部件应该放在哪里，左边栏还是右边栏
        position: left
        type: categories
        # 推荐链接小部件配置
    -
        # 小部件应该放在哪里，左边栏还是右边栏
        position: left
        type: links
        # 网站的名称和url
        links:
            威廉: 'https://bupt.dev/'
            叶子: 'https://yukino.nl/'
   
    # 最近发布的小部件配置
    -
        # 小部件应该放在哪里，左边栏还是右边栏
        position: right
        type: recent_posts
    # 归档小部件的配置
    -
        #小部件应该放在哪里，左边栏还是右边栏
        position: right
        type: archives
    # 标签小部件的配置
    -
        #小部件应该放在哪里，左边栏还是右边栏
        position: right
        type: tags

# 插件配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/
plugins:
    # 启用页面启动动画
    animejs: true
    # 显示“back to top”按钮
    back_to_top: true
    # 百度Analytics插件设置
    # https://tongji.baidu.com
    baidu_analytics:
        # Baidu Analytics tracking ID
        tracking_id: 
    # Bing网站管理员工具插件设置
    # https://www.bing.com/toolbox/webmaster/
    bing_webmaster:
        # Bing网站管理员工具跟踪ID在<meta>标签
        tracking_id: 
    #BuSuanZi网站/页面查看计数器
    # https://busuanzi.ibruce.info
    busuanzi: true
    # CNZZ统计
    # https://www.umeng.com/web
    cnzz:
        # CNZZ tracker id
        id: 
        # CNZZ website id
        web_id: 
    # 提醒用户使用cookie
    # https://www.osano.com/cookieconsent/
    cookie_consent:
        # 合规管理类型。可以是"info"， "opt-in"或"opt-out"
        type: info
        # 弹出的主题。可以是“块”，“无边”，或“经典”
        theme: edgeless
        # 不管页面是否滚动，弹出是否应该保持静态
        static: false
        # 同意窗口应该显示在屏幕的哪个位置
        position: bottom-left
        # URL到您的网站的cookie政策
        policyLink: 'https://www.cookiesandyou.com/'
    # 启用lightGallery和Justified Gallery插件
    gallery: true
    # 谷歌Analytics插件设置
    # https://analytics.google.com
    google_analytics:
        # 谷歌分析跟踪ID
        tracking_id: 
    # Hotjar用户反馈插件
    # https://www.hotjar.com/
    hotjar:
        # Hotjar site id
        site_id: 
    #启用KaTeX数学排版支持
    # https://katex.org/
    katex: false
    # 启用MathJax数学排版支持
    # https://www.mathjax.org/
    mathjax: false
    # 启用过时的浏览器插件
    # http://outdatedbrowser.com/
    outdated_browser: false
    # 在页面加载时在页面顶部显示一个进度条
    progressbar: true
    # Statcounter的数据
    # https://statcounter.com/
    statcounter:
        # Statcounter project id
        project: 
        # Statcounter project security code
        security: 
    # Twitter转换跟踪插件设置
    # https://business.twitter.com/en/help/campaign-measurement-and-analytics/conversion-tracking-for-websites.html
    twitter_conversion_tracking:
        # Twitter Pixel ID
        pixel_id: 
#CDN提供商设置
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL template of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    # Name or URL template of the webfont CDN provider
    fontcdn: google
    # Name or URL of the fontawesome icon font CDN provider
    iconcdn: fontawesome
